module.exports = (data) => {
  const stream = {
    key: { type: "string", message: "something went wrong" },
    index: "number",
    codec_name: "string",
    codec_long_name: "string",
    profile: "number",
    codec_type: "string",
    codec_time_base: "string",
    codec_tag_string: "string",
    codec_tag: "string",
    width: "number",
    height: "number",
    coded_width: "number",
    coded_height: "number",
    has_b_frames: "number",
    sample_aspect_ratio: "string",
    display_aspect_ratio: "string",
    pix_fmt: "string",
    level: "string",
    color_range: "string",
    color_space: "string",
    color_transfer: "string",
    color_primaries: "string",
    chroma_location: "string",
    field_order: "string",
    timecode: "string",
    refs: "number",
    id: "string",
    r_frame_rate: "string",
    avg_frame_rate: "string",
    time_base: "string",
    start_pts: "number",
    start_time: "number",
    duration_ts: "string",
    duration: "string",
    bit_rate: "string",
    max_bit_rate: "string",
    bits_per_raw_sample: "string",
    nb_frames: "string",
    nb_read_frames: "string",
    nb_read_packets: "string",
    sample_fmt: "string",
    sample_rate: "number",
    channels: "number",
    channel_layout: "string",
    bits_per_sample: "number",
    disposition: {
      key: "any",
      default: "number",
      dub: "number",
      original: "number",
      comment: "number",
      lyrics: "number",
      karaoke: "number",
      forced: "number",
      hearing_impaired: "number",
      visual_impaired: "number",
      clean_effects: "number",
      attached_pic: "number",
      timed_thumbnails: "number",
    },
    rotation: "string" || "number",
  };
};

const FfprobeFormat = {
  key: "any",
  filename: "string",
  nb_streams: "number",
  nb_programs: "number",
  format_name: "string",
  format_long_name: "string",
  start_time: "number",
  duration: "number",
  size: "number",
  bit_rate: "number",
  probe_score: "number",
  tags: "string" || "number",
};

let data = {
  fieldname: "video",
  originalname: "blob",
  encoding: "7bit",
  mimetype: "application/octet-stream",
  buffer: "",
  size: 832375,
  streams: [
    {
      index: 0,
      codec_name: "h264",
      codec_long_name: "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
      profile: "High",
      codec_type: "video",
      codec_tag_string: "avc1",
      codec_tag: "0x31637661",
      width: 1920,
      height: 1080,
      coded_width: 1920,
      coded_height: 1080,
      closed_captions: 0,
      film_grain: 0,
      has_b_frames: 1,
      sample_aspect_ratio: "N/A",
      display_aspect_ratio: "N/A",
      pix_fmt: "yuvj420p",
      level: 41,
      color_range: "pc",
      color_space: "smpte170m",
      color_transfer: "bt470m",
      color_primaries: "bt709",
      chroma_location: "left",
      field_order: "progressive",
      refs: 1,
      is_avc: "true",
      nal_length_size: 4,
      id: "0x1",
      r_frame_rate: "24000/1001",
      avg_frame_rate: "24000/1001",
      time_base: "1/24000",
      start_pts: 0,
      start_time: 0,
      duration_ts: 231231,
      duration: 9.634625,
      bit_rate: 22473522,
      max_bit_rate: "N/A",
      bits_per_raw_sample: 8,
      nb_frames: 231,
      nb_read_frames: "N/A",
      nb_read_packets: "N/A",
      extradata_size: 40,
      tags: {
        creation_time: "2022-02-17T20:10:22.000000Z",
        language: "eng",
        vendor_id: "[0][0][0][0]",
      },
      disposition: {
        default: 1,
        dub: 0,
        original: 0,
        comment: 0,
        lyrics: 0,
        karaoke: 0,
        forced: 0,
        hearing_impaired: 0,
        visual_impaired: 0,
        clean_effects: 0,
        attached_pic: 0,
        timed_thumbnails: 0,
        non_diegetic: 0,
        captions: 0,
        descriptions: 0,
        metadata: 0,
        dependent: 0,
        still_image: 0,
      },
    },
    {
      index: 1,
      codec_name: "pcm_s16le",
      codec_long_name: "PCM signed 16-bit little-endian",
      profile: "unknown",
      codec_type: "audio",
      codec_tag_string: "sowt",
      codec_tag: "0x74776f73",
      sample_fmt: "s16",
      sample_rate: 48000,
      channels: 2,
      channel_layout: "unknown",
      bits_per_sample: 16,
      initial_padding: 0,
      id: "0x2",
      r_frame_rate: "0/0",
      avg_frame_rate: "0/0",
      time_base: "1/48000",
      start_pts: 0,
      start_time: 0,
      duration_ts: 456456,
      duration: 9.5095,
      bit_rate: 1536000,
      max_bit_rate: "N/A",
      bits_per_raw_sample: "N/A",
      nb_frames: 456456,
      nb_read_frames: "N/A",
      nb_read_packets: "N/A",
      tags: {
        creation_time: "2022-02-17T20:10:22.000000Z",
        language: "eng",
        vendor_id: "[0][0][0][0]",
      },
      disposition: {
        default: 1,
        dub: 0,
        original: 0,
        comment: 0,
        lyrics: 0,
        karaoke: 0,
        forced: 0,
        hearing_impaired: 0,
        visual_impaired: 0,
        clean_effects: 0,
        attached_pic: 0,
        timed_thumbnails: 0,
        non_diegetic: 0,
        captions: 0,
        descriptions: 0,
        metadata: 0,
        dependent: 0,
        still_image: 0,
      },
    },
  ],
  format: {
    filename: "./test/d3bb07bc-8755-468d-a46a-993bc0c0ef78.MOV",
    nb_streams: 2,
    nb_programs: 0,
    format_name: "mov,mp4,m4a,3gp,3g2,mj2",
    format_long_name: "QuickTime / MOV",
    start_time: 0,
    duration: 9.634625,
    size: 29143927,
    bit_rate: 24199324,
    probe_score: 100,
    tags: {
      major_brand: "qt  ",
      minor_version: "537331968",
      compatible_brands: "qt  niko",
      creation_time: "2022-02-17T20:10:22.000000Z",
    },
  },
  chapters: [],
};
